usb: dwc3: fix compilation if CONFIG_USB_DWC3_OTG is not selected
Current DWC3 cannot be compiled if CONFIG_USB_DWC3_OTG is not selected.
It will fail with this log:

  CC      drivers/usb/dwc3/core.o
/home/pjnozisk/main/linux/kernel-next/drivers/usb/dwc3/core.c: In
function 'dwc3_core_init':
/home/pjnozisk/main/linux/kernel-next/drivers/usb/dwc3/core.c:340:28:
error: 'ULPI_VENDOR_ID_LOW' undeclared (first use in this function)
/home/pjnozisk/main/linux/kernel-next/drivers/usb/dwc3/core.c:340:28:
note: each undeclared identifier is reported only once for each function
it appears in
make[5]: *** [drivers/usb/dwc3/core.o] Error 1
make[4]: *** [drivers/usb/dwc3] Error 2
make[3]: *** [drivers/usb] Error 2
make[2]: *** [drivers] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/home/pjnozisk/main/linux/kernel-next'
make: *** [build_bzImage] Error 2

This patch fixed compilation.

Fixed conflict porting 3.10 to 4.x

Signed-off-by: David Cohen <david.a.cohen@intel.com>

Conflicts:
	drivers/usb/dwc3/core.c

Change-Id: I9e1a7e01a5eaad82326d756b15a08c04b8204a8a